### ISSUE TITLE
V6 Cryptography - Perfect Forward Secrecy

### ISSUE THREAD

**Issue by danielcuthbert** [OWASP/ASVS#2252] opened 2024-11-05 14:49 UTC
<img width="930" alt="Screenshot 2024-11-05 at 14 20 33" src="https://github.com/user-attachments/assets/b27d642e-3cb1-43d2-84e5-8050fe0c459d">

Scheme | Domain Parameters
-- | --
RSA | k >= 2048
Diffie-Hellman (DH) | (L, N) parameters: L >= 2048 & N >= 224
Elliptic Curve Diffie-Hellman (ECDH) | f >= 224

</markdown-accessiblity-table>
<p dir="auto"></p>

**Comment by danielcuthbert** [comment] 2024-11-06 08:26
An interesting comment, thank you. Firstly I guess we need context here. Both RSA and DHE do support PFS and we need transient key pairs (temp keys) in order to encrypt $stuff$ for that conversation. 

We have specified that both RSA and DHE need k >= 2048, which is the minimum amount required to suppport PFS (same goes for DH). So yes, they do support it in the above

However, there is a computational impact say on TLS of using PFS, and there is the issue of backwards compatability with older clients. 

Im closing this for now but by all means open a new issue if this isn't clear

**Comment by randomstuff** [comment] 2024-11-06 20:21
Proposed generic requirement:

> 9.2.X Verify than for all communications using an encrypted protocols (TLS, SSH) the communication provides forward secrecy with respect to the long term private keys when communicating with modern clients. Non-forward secret communication might still be supported only for compatibility with old client which do not support it and if such compatibility is required.

This generic requirement could be specialized into more specific requirement about TLS (?). Proposed requirement about forward secrecy with respect to the client private key

> 9.4.X Verify than for all communications using TLS provides forward secrecy with respect to server private key when communicating with modern clients. Key exchanges such as RSA transport, static diffie-hellman, static ECDH (for TLS 1.2) must not be used.

Is 9.4.X with existing requirement such as 9.4.1? ("latest recommended cipher suites")

Some questions/comments:

* I would consider a requirement about forward secrecy with respect to the client private key in TLS (i.e. rsa_fixed_dh, dss_fixed_dh). I don't know if this has been used in practice and I don't believe this has been used much anyway.
* I'm not including requirements about forward secrecy with TLS PSK as this is quite niche (outside of TLS 1.3 session resumption).
* Before TLS 1.3 and when using TLS 1.3 with psk_ke, there is no forward secrecy with respect to the session secret. This might need to be mitigated. More generally, there are considerations wrt TLS sessions secrets which might need to be included.

**Comment by randomstuff** [comment] 2024-11-06 21:22
> We have specified that both RSA and DHE need k >= 2048, which is the minimum amount required to suppport PFS (same goes for DH). So yes, they do support it in the above

I believe we are talking about the RSA transport scheme here (i.e. sending a shared secret to the peer encrypted using the peer's RSA public key) which don't provide forward secrecy with respect to the peer's RSA private key, right?

**Comment by unprovable** [comment] 2024-11-11 14:17
It's really unclear which kind of forward secrecy you're referring to. PFS uses negotiated long term keys followed by per-message session keys derived sequentially from messages that have been sent so far (hence the 'forward secrecy' name). This makes sense when you talk about TLS or Whisper protocol, but not generally for KEX. If you can elaborate your argument, @randomstuff, this would make it easier to answer. M.

**Comment by randomstuff** [comment] 2024-11-11 16:15
AFAIU, forward secrecy means that if the long term secrets used in the key exchange protocol are disclosed, previous sessions are not compromised (previous session/transient keys cannot be recovered).

I understand that the RSA KEX discussed here is the "RSA transport" scheme where peer A uses RSA to send an some encrypted session key material to the peer B (using peer B's public key).  Is this what we are talking about here?

If this is what we are talking about, do we agree that this scheme does not provide forward secrecy (because if B's public key is disclosed the session key material can be decrypted)? If so, are there any reasons for recommending it (outside of compatibility)?

**Comment by unprovable** [comment] 2024-11-11 18:15
Can you do me a favour and name a scheme that does support PFS so I can
better understand where you are coming from? Many thanks! M

**Comment by randomstuff** [comment] 2024-11-11 18:25
Ephemeral Diffie-Hellman?

**Comment by randomstuff** [comment] 2024-11-11 19:28
I did not intent my question to be about TLS ciphersuites.

I agree that you can build some key exchange scheme on top of RSA which features forward secrecy. From a theoretical standpoint, my argument is therefore moot. However, is such a scheme ever used anywhere in practice?

In practice, with the text as it is, isn't there t a risk that we may encourage using a non-forward-secure scheme where a we send a session secret encrypted with a static RSA key?

**Comment by unprovable** [comment] 2024-11-11 19:43
"Key Exchange" is not synonymous with "uses PFS". As I mentioned, there are
protocols that use it, but it is a recommendation to use PFS where it is an
optional feature, rather than a requirement to be placed on KEX. I suggest
we put it there. M.

**Comment by tghosth** [comment] 2024-11-20 07:15
@randomstuff is there any further action here

**Comment by randomstuff** [comment] 2024-11-20 20:52
We can this as duplicate of #2215.

**Closed** 2024-11-22 08:06 UTC
Labels: 2) Awaiting response, _5.0 - prep, V6
