### ISSUE TITLE
Add access token requirement for preventing "key confusion"

### ISSUE THREAD

**Issue by TobiasAhnoff** [OWASP/ASVS#2361] opened 2024-11-09 09:36 UTC
Add access token requirement for preventing "key confusion".

This is part of "cleaning up 3.5" see https://github.com/OWASP/ASVS/issues/1917#issuecomment-2466143871

> Verify that the cryptographic keys for tokens belong to the token issuer. If both symmetric (MAC) and asymmetric (digital signatures) algorithms needs to be supported, additional controls must prevent key confusion. For JWTs the 'iss' claim must be validated to be a preconfigured expected value.

**Comment by elarlang** [comment] 2024-11-09 13:35
I don't think it is JWT or token specific requirement - those who have worked with V6 maybe can hint is this covered there already.

Also it is on the limit with the scope. You need to have access to issuer setup that is a bit out of scope from application point of view. And if you have access, then I think it is more a question of handling keys in general? (ping @randomstuff @danielcuthbert )

For tokens we additionally have of will have requirement for validating the 'iss' claim.

**Comment by elarlang** [comment] 2024-11-11 18:19
"key confusion" is mentioned at the moment in current version of 3.5.5:
> Verify that only algorithms on an allowlist can be used to create and verify cryptographically secured tokens, for a given context. The allowlist should include the permitted algorithms, ideally only either symmetric or asymmetric algorithms, and should not include the 'None' algorithm. **If both symmetric and asymmetric are needed, additional controls should prevent key confusion**.

The requirement itself is discussed in the issue #2204 .  Is this a recommendation to split the current 3.5.5, is it a duplicate of current 3.5.5 and should be closed or it provides some new aspect that is not covered yet?

**Comment by TobiasAhnoff** [comment] 2024-11-13 06:28
The suggestion was to split split the current 3.5.5 and have "key confusion" together with "Verify that the cryptographic keys for tokens belong to the token issuer" and to provide an example for JWTs with "For JWTs the 'iss' claim must be validated to be a preconfigured expected value".

I think is is good to split, since "using strong alg" and "key confusion" are different things, you could use strong algs and still confuse keys.

**Comment by TobiasAhnoff** [comment] 2024-11-16 09:03
Given that we decide to split, is this good as a requirement for the "key confusion" part?

> Verify that the cryptographic keys for tokens belong to the token issuer. If both symmetric (MAC) and asymmetric (digital signatures) algorithms needs to be supported, additional controls must prevent key confusion. For JWTs the 'iss' claim must be validated to be a preconfigured expected value.

**Comment by randomstuff** [comment] 2024-11-16 17:04
Would it be "needs to be supported" or "are supported"?

Maybe we need to say that this is for token *verification* (not generation)?

> Verify that the cryptographic keys used for for token validation belong to the token issuer.

Nitpick, there is a missing comma:

> Verify that the cryptographic keys for tokens belong to the token issuer. If both symmetric (MAC) and asymmetric (digital signatures) algorithms needs to be supported, additional controls must prevent key confusion. For JWTs, the 'iss' claim must be validated to be a preconfigured expected value.

**Comment by TobiasAhnoff** [comment] 2024-11-17 08:55
Perhaps this?

> Verify that the cryptographic keys used for token validation belong to the token issuer. If both symmetric (MAC) and asymmetric (digital signatures) algorithms are supported, additional controls must prevent key confusion. For JWTs, the 'iss' claim must be validated to be a preconfigured expected value.

**Comment by elarlang** [comment] 2024-11-17 09:07
Some more clarifications to document:
1) how do you test/verify it?
2) how it is different from 3.5.7 (_Verify that key material that is used to validate cryptographically secured tokens is from trusted pre-configured sources for the token issuer, preventing attackers from specifying untrusted sources and keys. For JWTs and other JWS structures, headers such as 'jku', 'x5u', and 'jwk' must be validated against an allowlist of trusted sources._))

**Comment by randomstuff** [comment] 2024-11-17 12:25
> how it is different from 3.5.7?

3.5.7 is about using the correct cryptographic material for validating the token.

The one we are discussing here is supposed to be about key confusion but actually covers:

1. key confusion
2. correct cryptographic material

We should probably better focus on (1) and remove (2) from this requirement.

Alternatively or in addition, this might be part of a more general cryptography requirement about verifying that each key is used with its intended cryptographic usage:

* honoring key type and key usage
* for JWK, this would mean enforcing "kty", "use", "key_ops", "alg"
* for X.509, this would mean honoring key type, key usage, extended key usage

**Comment by TobiasAhnoff** [comment] 2024-11-18 17:37
> how it is different from 3.5.7?

Maybe 3.5.7 could include issuer claim, like this?

> V3.5.7 Verify that key material that is used to validate cryptographically secured tokens is from trusted pre-configured sources for the token issuer, preventing attackers from specifying untrusted sources and keys. For JWTs and other JWS structures, the 'iss' claim and headers such as 'jku', 'x5u', and 'jwk' must be validated against an allowlist of trusted sources.

I think this would address the "key confusion" scenario as well.

It is also probably good to open a new issue for a "more general cryptography requirement about verifying that each key is used with its intended cryptographic usage" in V6

**Comment by randomstuff** [comment] 2024-11-18 20:30
> For JWTs, ensure that token verification operations explicitly specify which algorithm is to be used.

Is this necessary? Would it be OK if I'm using `algorithms=["ES384", "ES512"]`? It might be enough to avoid mixing MACs and digital signature in the list of allowed  algorithms.

Should we say "For example, for JWTs, …"?

**Comment by ryarmst** [comment] 2024-11-18 21:25
Good point, how about something more specific to key confusion: 

> Verify that key material is only used with algorithms intended for it to prevent key confusion attacks. For example, JWT verification operations must not permit a public key to be used as an HMAC secret.

**Comment by tghosth** [comment] 2024-11-22 09:20
Please see my comment here: https://github.com/OWASP/ASVS/issues/2360#issuecomment-2493294316

@ryarmst @TobiasAhnoff @randomstuff

**Comment by elarlang** [comment] 2024-12-05 20:17
Is it solved now via #2360 > #2431?

**Closed** 2024-12-06 11:07 UTC
Labels: _5.0 - prep, V52
