### ISSUE TITLE
7.1.1 and 7.1.2 Not Pentestable

### ISSUE THREAD

**Issue by ossie-git** [OWASP/ASVS#640] opened 2019-04-17 03:17 UTC
Technically, 7.1.1 and 7.1.2 shouldn't be in L1 because they are not pentestable.  Then again, hopefully they become Level 1 - O https://github.com/OWASP/ASVS/issues/639 :)

**Comment by davewichers** [comment] 2019-05-14 20:53
Don't you think the existing comment in ASVS 4.0 right before these requirements:

"V7.1 covers OWASP Top 10 2017:A10. As 2017:A10 and this section are not penetration testable, it's important for:
• Developers to ensure full compliance with this section, as if all items were marked as L1
• Penetration testers to validate full compliance of all items in V7.1 via interview, screenshots, or assertion"

Addresses this point?

**Comment by tghosth** [comment] 2019-05-19 17:18
I agree with @davewichers. The pentestability issue is an ongoing question which I will leave for #63 9 for now.

**Closed by tghosth** 2019-05-19 17:18 UTC

**Comment by davewichers** [comment] 2019-05-19 19:05
Can you remove the inadvertent space in your comment above, so it actually
refers to: #63 <https://github.com/OWASP/ASVS/issues/63>9 as intended?

**Comment by tghosth** [comment] 2019-05-20 20:37
🤦‍♂️ thanks

**Comment by kwwall-gri** [comment] 2021-11-02 17:35
> Don't you think the existing comment in ASVS 4.0 right before these requirements:
> 
> "V7.1 covers OWASP Top 10 2017:A10. As 2017:A10 and this section are not penetration testable, it's important for: • Developers to ensure full compliance with this section, as if all items were marked as L1 • Penetration testers to validate full compliance of all items in V7.1 via interview, screenshots, or assertion"
> 
> Addresses this point?

@davewichers - No, I don't, unless you are doing white box or gray box pen testing. But ASVS states:
> Level 1 is the only level that is completely penetration testable using humans. All others require access to
documentation, source code, configuration, and the people involved in the development process. However, even if
L1 allows "black box" (no documentation and no source) testing to occur, it is not effective assurance and must
stop

It seems clear from the descriptions for ASVS requirement IDs 7.1.1 and 7.1.2 that you are either going to need access to the source code or access to the log files to verify these. (And probably the source code, since you wouldn't know if you've "fired" all the relevant logging events.) IMO, interviews and screenshots are not going to cut it. And I'm not sure that "assertions" are worth anything, especially given the proclivity for humans making so many assumptions and for not remembering all the details in complex software systems. So by that consideration, these should be L2, not L1. If you want an "out" to justify making these 2 L1, then just flat out state something like "While some of these are not verifiable without access o source code, we believe that some of them are important enough to _always_ be done, and thus are making them L1."

**Comment by jmanico** [comment] 2021-11-02 17:55
I think we should fully discard the pentestable discussion and just say all requirements require various forms of assessment. 

ASVS should be risk-based. I feel the three categories should move to something more in alignment with SP-NIST 800-63's various AAL's levels and similar. The fact that our three levels are based on testing methods is - very different than any other standard in the industry, and not for the better, IMO.

**Comment by kwwall-gri** [comment] 2021-11-02 18:55
@jmanico - I agree, it should be risk-based, not 'ease of verification' based. However, there is still _some_ value in knowing whether something can be validated via black box testing. E.g., I have been asked to get our QA teams involved on some basic security testing as part of BSIMM 11's ST1.1 SSDL touchpoint (" Ensure QA performs edge/
boundary value condition testing"), so knowing what they potentially can validate from a black box is useful, although probably not so much as we think it is. But if we want to keep it, it's easier enough to just create a new separate column in the spreadsheet "Black box testable?".

**Comment by cmlh** [comment] 2021-11-02 23:57
I'd prefer it effort [objective] based as risk is subjectively defined "_in the eye of the beholder_"

Common Criteria is verified to a level of effort to quote https://github.com/OWASP/ASVS/issues/1108#issuecomment-955619482 to which its relevance is below:

> Mike Boberski based ASVS ToV (i.e. Common Criteria)
