### ISSUE TITLE
ASVS 5-V7 Error Logging

### ISSUE THREAD

**Issue by wittjoe1** [OWASP/ASVS#1749] opened 2023-10-11 10:18 UTC
References to "OWASP Top 10 2017:A10" should be updated to latest edition "OWASP Top 10 2021:A9"

**Comment by elarlang** [comment] 2023-10-11 10:41
Thank you for reporting, but I close it as duplicate of https://github.com/OWASP/ASVS/issues/1150.

**Closed** 2023-10-11 10:42 UTC
