### ISSUE TITLE
13.3.2 is too specific, kinda obsolete and effectively duplicates 13.2.6, suggest removal.

### ISSUE THREAD

**Issue by tghosth** [OWASP/ASVS#1525] opened 2023-01-24 13:32 UTC
Requirement history:

| # | Description | L1 | L2 | L3 | CWE |
| :---: | :--- | :---: | :---: | :---: | :---: |
| **13.3.2** | Verify that the message payload is signed using WS-Security to ensure reliable transport between client and service. | | ✓ | ✓ | 345 |
| **[13.3.2](https://github.com/OWASP/ASVS/commit/b29ed7628b5fed80c8a9c593fe1fa311d1d42a35)** | Verify that the message payload is signed to ensure reliable transport between client and service, using JSON Web Signing or WS-Security for SOAP requests. |  | ✓ | ✓ | 345 |
| **[18.7](https://github.com/OWASP/ASVS/blame/7d1a0c7dd377734cbbd223d9f0e9019b9644084e/4.0/en/0x23-V18-API.md)** | Verify that the message payload is signed to ensure reliable transport between client and service, using JSON Web Signing or WS-Security for SOAP requests. |  | ✓ | ✓ | 345 |

18.7 appeared in ASVS 3.0.1 as 18.9.

Requirement [13.2.6](https://appsecg.host/13.2) (also CWE 345) currently says:

> Verify that the message headers and payload are trustworthy and not modified in transit. Requiring strong encryption for transport (TLS only) may be sufficient in many cases as it provides both confidentiality and integrity protection. Per-message digital signatures can provide additional assurance on top of the transport protections for high-security applications but bring with them additional complexity and risks to weigh against the benefits.

There is [currently a proposal](https://github.com/OWASP/ASVS/issues/1207#issuecomment-1374874043) in #1207 to change it to:

> [MODIFIED] Verify that per-message digital signatures are used to provide additional assurance on top of transport protections for requests/transactions which are highly sensitive or which traverse a number of systems without an uninterrupted TLS connection.

As such, I would propose just dropping this requirement entirely.

**Comment by elarlang** [comment] 2023-05-28 09:32
Why it obsolete? (I don't know the topic)

By description I agree it is duplicate of 13.2.6

**Comment by jmanico** [comment] 2023-07-10 13:54
I like this change!

**Comment by tghosth** [comment] 2023-07-10 15:22
I have opened #1685 to resolve this. This also moves it to section 13.1 because I think this is more generic then just a REST requirement.

**Closed** 2023-07-13 08:12 UTC
Labels: 6) PR awaiting review, _5.0 - prep
