### ISSUE TITLE
1.2.5

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1859] opened 2024-02-06 21:34 UTC
This looks out of place and should go with the rest of the password requirements.

1.2.5 | [ADDED] Verify that a list of context specific words are documented in order to prevent their use in passwords.
-- | --

**Comment by elarlang** [comment] 2024-02-07 06:34
Currently ,we put "documentation requirements" to V1 and implementation requirements" to each category. Do we keep this structure, it is up for discussion (https://github.com/OWASP/ASVS/discussions/1831).

As it where it should be (by current logic), I close this as duplicate of discussion #1831.

**Closed by elarlang** 2024-02-07 06:34 UTC
