### ISSUE TITLE
Clarification for 2.10.1

### ISSUE THREAD

**Issue by wet-certitude** [OWASP/ASVS#1007] opened 2021-05-27 08:33 UTC
I am a bit unclear on the requirement [2.10.1](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x11-V2-Authentication.md#v210-service-authentication).

> Verify that intra-service secrets do not rely on unchanging credentials such as passwords, API keys or shared accounts with privileged access.

I am not exactly sure what an "intra-service secret" would be. Does "service" refer to the whole application? In this case, I assume this would be service accounts like database accounts etc. If "service" is meant to be e.g. a microservice (a single container in an application), I don't understand it ("inter-service secret" would make more sense in that case).

Assuming the former, what would be an acceptable authenticator for services? Assuming an application that communicates with a Postgres DB, how should authentication be implemented? Passwords and storing a private key for an TLS cert are not allowed, as these are, I assume, unchanging. What would constitute a non-non-changing credential?

For L3 a HSM is required to store these secrets. Does that mean that e.g. TLS crypto operations for authenticating against another service are supposed to be offloaded to an HSM (e.g. the application uses a TLS client certificate stored in an HSM to authenticate against the Postgres DB)? In that case, where should the credentials for accessing the HSM be stored (for HSMs with a network interface)? Or is an internal HSM (e.g. PCI Express card) required? Simply storing the secret in an HSM an retrieving it in my opinion does not make any sense (the HSM can only properly protect secrets when the whole crypto operation is offloaded to it, e.g. the HSM can protect a private key by taking on all the decryption/signature operations an never revealing the actual private key).

**Comment by wet-certitude** [comment] 2021-05-27 09:55
I just figured that there are several ways to interpret that sentence:

---
* Intra-service secrets may not rely on unchanging credentials, such as:
  * passwords
  * API keys
  * shared accounts with privileged access

I.e. "shared accounts with privileged access" is an example of an unchanging credential.

---
* Intra-service secrets may not rely on:
  * unchanging credentials such as passwords or API keys 
  * shared accounts with privileged access

I.e. both "unchanging credentials such as passwords, API keys" and "shared accounts with privileged access" are independent and both prohibited. 

---
* Intra-service secrets may not rely on unchanging credentials, such as:
  * passwords
  * API keys
  * shared accounts
* IF THEY HAVE privileged access

---
I suspect the last interpretation is correct, as it makes the most sense for me (you wouldn't want intra-service secrets to have privileged access, though the "unchanging" is still sort of unclear).

(I'm not a grammar expert, maybe there is a definitively correct interpretation)

**Comment by jmanico** [comment] 2021-09-24 02:45
This is a duplicate of https://github.com/OWASP/ASVS/issues/1032 :)

**Closed by jmanico** 2021-09-24 02:45 UTC
Labels: duplicate
