### ISSUE TITLE
2.10.3 looks like a repeat of V2.4 Credential Storage

### ISSUE THREAD

**Issue by jmanico** [OWASP/ASVS#1616] opened 2023-04-18 14:57 UTC
2.10.3 is covered already in V2.4 Credential Storage

2.10.3 | Verify that passwords are stored with sufficient protection to prevent offline recovery attacks, including local system access. |   | ✓ | ✓ | 522
-- | -- | -- | -- | -- | --

**Comment by elarlang** [comment] 2023-04-27 09:07
If we look at category names as well, we can interpret it like this:
* V2.10 Service Authentication - passwords stored in the application to access (external) services - it must be possible to get the plain text of the password
* V2.4 Credential Storage - passwords stored in the application for external users and/or services to access the application - no need to read the password plain-text version

**Comment by tghosth** [comment] 2023-07-10 09:41
We need to make all this clearer during the rework

**Comment by elarlang** [comment] 2024-10-08 08:50
. o O ( can not see any proposal to review )

**Comment by tghosth** [comment] 2024-10-08 09:08
Current situation:

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **2.4.1** | [MODIFIED, MERGED FROM 2.4.3, 2.4.4] Verify that user passwords are stored using an approved password hashing algorithm that is securely configured according to current guidance. | | ✓ | ✓ | 916 | 5.1.1.2 |

| # | Description | L1 | L2 | L3 | CWE | [NIST &sect;](https://pages.nist.gov/800-63-3/sp800-63b.html) |
| :---: | :--- | :---: | :---: | :---: | :---: | :---: |
| **2.10.3** | [DELETED, DUPLICATE OF 2.10.4] | | | | | |
| **2.10.4** | [GRAMMAR] Verify passwords, integrations with databases and third-party systems, seeds and internal secrets, and API keys are managed securely and not included in the source code or stored within source code repositories. Such storage should resist offline attacks. The use of a secure software key store (L1), hardware TPM, or an HSM (L3) is recommended for password storage. | | ✓ | ✓ | 798 | |

I think 2.10.4 needs to be clearer as the wording is currently a little weird.

However, I am going to open a separate issue #2130 as I think this current issue is no longer relevant.

**Comment by tghosth** [comment] 2024-10-08 09:08
> . o O ( can not see any proposal to review )

LOL you really do get every notification

**Closed by tghosth** 2024-10-08 09:08 UTC
Labels: 1) Discussion ongoing, _5.0 - prep, V2
