### ISSUE TITLE
Online browsable ASVS

### ISSUE THREAD

**Issue by jefmeijvis** [OWASP/ASVS#1624] opened 2023-05-22 13:09 UTC
Hi all,

Less of a content and more a presentation related question:
Is there a "browsable online version" of ASVS? 
I've found the master data files in this repository, as well as the downloadable pdf/csv/word documents.
But is there a website that allows people to browse the standard?

To illustrate this with an example, to view a specific CAPEC attack pattern, such as CAPEC-68, you would be able to visit the following webpage: https://capec.mitre.org/data/definitions/68.html

Does a similar site/project exists for ASVS?

**Comment by elarlang** [comment] 2023-05-22 14:23
The short answer is "no" and at the moment we lack resources to create one.

**Comment by elarlang** [comment] 2023-05-22 14:39
We have separate proposal issue for that, closing as duplicate of https://github.com/OWASP/ASVS/issues/895

**Closed by elarlang** 2023-05-22 14:39 UTC
